language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - tip

script:
  - GO111MODULE=on go mod vendor
  - if git status --short | grep --quiet 'vendor/'; then
        echo "'vendor/' directory needs to be updated.";
        travis_terminate 1;
    fi
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
